[package]
name = "topogen"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["bench"]

[dependencies]
bit-vec = "0.6"
petgraph = { version = "0.6", optional = true }

[dev-dependencies]
proptest = "1.1"
